[package]
name = "juniper_tests"
version = "0.1.0"

[dependencies]
juniper = { version = "0.10.0", path = "../juniper" }
serde_json = { version = "1" }

[dev-dependencies]
fnv = "1.0.3"
indexmap = "1.0"

[[test]]
name = "integration_tests"
path = "src/lib.rs"
harness = true
