[[pre-release-replacements]]
file = "../book/src/servers/rocket.md"
exactly = 1
search = "juniper_rocket = \"[^\"]+\""
replace = "juniper_rocket = \"{{version}}\""

[[pre-release-replacements]]
file = "CHANGELOG.md"
exactly = 1
search = "## master"
replace = "## [{{version}}] · {{date}}\n[{{version}}]: /../../tree/{{crate_name}}%40{{version}}/{{crate_name}}"

[[pre-release-replacements]]
file = "README.md"
exactly = 3
search = "graphql-rust/juniper/blob/[^/]+/"
replace = "graphql-rust/juniper/blob/{{crate_name}}%40{{version}}/"
