[package]
name = "juniper_2018_edition_tests"
version = "0.1.0"
authors = ["Christoph Herzog <chris@theduke.at>"]
edition = "2018"

[dependencies]
juniper = { version = "0.11", path = "../../juniper" }
