
[tasks.build-verbose]
args = ["build", "--verbose"]

[tasks.test-verbose]
args = ["test", "--verbose"]

[tasks.release]
disabled = true
[tasks.release-some]
disabled = true
[tasks.release-local-test]
disabled = true
[tasks.release-some-local-test]
disabled = true
[tasks.release-dry-run]
disabled = true
[tasks.release-some-dry-run]
disabled = true
