(function() {var implementors = {};
implementors["libc"] = [];implementors["lazy_static"] = [];implementors["openssl"] = ["impl&lt;R,&nbsp;F&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.FnOnce.html' title='core::ops::FnOnce'>FnOnce</a>() for <a class='struct' href='https://doc.rust-lang.org/nightly/std/panic/struct.AssertUnwindSafe.html' title='std::panic::AssertUnwindSafe'>AssertUnwindSafe</a>&lt;F&gt; <span class='where'>where F: <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.FnOnce.html' title='core::ops::FnOnce'>FnOnce</a>() -&gt; R</span>","impl&lt;'a,&nbsp;A,&nbsp;R&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.FnOnce.html' title='core::ops::FnOnce'>FnOnce</a>&lt;A&gt; for <a class='struct' href='https://doc.rust-lang.org/nightly/alloc/boxed/struct.Box.html' title='alloc::boxed::Box'>Box</a>&lt;<a class='trait' href='https://doc.rust-lang.org/nightly/alloc/boxed/trait.FnBox.html' title='alloc::boxed::FnBox'>FnBox</a>&lt;A,&nbsp;Output=R&gt; + 'a&gt;","impl&lt;'a,&nbsp;A,&nbsp;R&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.FnOnce.html' title='core::ops::FnOnce'>FnOnce</a>&lt;A&gt; for <a class='struct' href='https://doc.rust-lang.org/nightly/alloc/boxed/struct.Box.html' title='alloc::boxed::Box'>Box</a>&lt;<a class='trait' href='https://doc.rust-lang.org/nightly/alloc/boxed/trait.FnBox.html' title='alloc::boxed::FnBox'>FnBox</a>&lt;A,&nbsp;Output=R&gt; + 'a + <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Send.html' title='core::marker::Send'>Send</a>&gt;",];implementors["hyper"] = [];implementors["iron"] = ["impl&lt;'a,&nbsp;A,&nbsp;R&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.FnOnce.html' title='core::ops::FnOnce'>FnOnce</a>&lt;A&gt; for <a class='struct' href='https://doc.rust-lang.org/nightly/alloc/boxed/struct.Box.html' title='alloc::boxed::Box'>Box</a>&lt;<a class='trait' href='https://doc.rust-lang.org/nightly/alloc/boxed/trait.FnBox.html' title='alloc::boxed::FnBox'>FnBox</a>&lt;A,&nbsp;Output=R&gt; + 'a&gt;","impl&lt;'a,&nbsp;A,&nbsp;R&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.FnOnce.html' title='core::ops::FnOnce'>FnOnce</a>&lt;A&gt; for <a class='struct' href='https://doc.rust-lang.org/nightly/alloc/boxed/struct.Box.html' title='alloc::boxed::Box'>Box</a>&lt;<a class='trait' href='https://doc.rust-lang.org/nightly/alloc/boxed/trait.FnBox.html' title='alloc::boxed::FnBox'>FnBox</a>&lt;A,&nbsp;Output=R&gt; + 'a + <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Send.html' title='core::marker::Send'>Send</a>&gt;",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
