[tasks.build-verbose]
condition = { channels = ["nightly", "beta"] }

[tasks.build-verbose.windows]
condition = { channels = ["nightly", "beta"] }

[tasks.test-verbose]
condition = { channels = ["nightly", "beta"] }

[tasks.test-verbose.windows]
condition = { channels = ["nightly", "beta"] }

[tasks.ci-coverage-flow]
condition = { channels = ["nightly", "beta"] }

[tasks.ci-coverage-flow.windows]
disabled = true
