[tasks.build-verbose]
condition = { channels = ["nightly", "beta", "stable"]  }
condition_script = ["./juniper_warp/scripts/rustc_version_is_supported.sh"]

[tasks.build-verbose.windows]
condition = { channels = ["nightly", "beta", "stable"] }
condition_script = ["./juniper_warp/scripts/rustc_version_is_supported.sh"]

[tasks.test-verbose]
condition = { channels = ["nightly", "beta", "stable"] }
condition_script = ["./juniper_warp/scripts/rustc_version_is_supported.sh"]

[tasks.test-verbose.windows]
condition = { channels = ["nightly", "beta", "stable"] }
condition_script = ["./juniper_warp/scripts/rustc_version_is_supported.sh"]

[tasks.ci-coverage-flow]
condition = { channels = ["nightly", "beta", "stable"] }
condition_script = ["./juniper_warp/scripts/rustc_version_is_supported.sh"]

[tasks.ci-coverage-flow.windows]
disabled = true
