# This is needed as the release config is at a different path than the top-level
# release config.

[tasks.release]
args = ["release", "--config", "${CARGO_MAKE_WORKING_DIRECTORY}/release.toml", "${RELEASE_LEVEL}"]

[tasks.release-dry-run]
args = ["release", "--config", "${CARGO_MAKE_WORKING_DIRECTORY}/release.toml", "--dry-run", "${RELEASE_LEVEL}"]

[tasks.release-local-test]
args = ["release", "--config", "${CARGO_MAKE_WORKING_DIRECTORY}/release.toml", "--no-confirm", "--skip-publish", "--skip-push", "--skip-tag", "${RELEASE_LEVEL}"]

[env]
CARGO_MAKE_CARGO_ALL_FEATURES = ""

[tasks.build-verbose]
condition = { rust_version = { min = "1.29.0" } }

[tasks.build-verbose.windows]
condition = { rust_version = { min = "1.29.0" }, env = { "TARGET" = "x86_64-pc-windows-msvc" } }

[tasks.test-verbose]
condition = { rust_version = { min = "1.29.0" } }

[tasks.test-verbose.windows]
condition = { rust_version = { min = "1.29.0" }, env = { "TARGET" = "x86_64-pc-windows-msvc" } }

[tasks.ci-coverage-flow]
condition = { rust_version = { min = "1.29.0" } }

[tasks.ci-coverage-flow.windows]
disabled = true
