[package]
name = "warp_server"
version = "0.1.0"
authors = ["Tom Houlé <tom@tomhoule.com>"]

[dependencies]
warp = "0.1.0"
juniper_warp = { path = "../.." }
env_logger = "0.5.11"
log = "0.4.3"
juniper = { path = "../../../juniper", version = ">=0.9, 0.10.0", features = ["expose-test-schema", "serde_json"] }
